"""Dump a reference input/output pair so the GLSL port can be checked against
PyTorch numerically. A silent indexing error in the mat4 packing or the pixel
shuffle would otherwise look like 'slightly worse quality' forever."""
import json, numpy as np, torch
from pathlib import Path
from train import TinySR, CKPT, PATCHES

HERE = Path(__file__).resolve().parent
ck = torch.load(CKPT, map_location="cpu", weights_only=True)
m = TinySR(ck["filters"], ck["layers"]); m.load_state_dict(ck["state"]); m.eval()

d = np.load(PATCHES)
# Quantise to 8 bits FIRST: the browser will feed the net an 8-bit canvas, so
# PyTorch must see the exact same values or the comparison measures rounding.
lr = d["lr"][17].astype(np.float32)          # one real 48x48 luma patch
lr = np.round(lr * 255.0) / 255.0
with torch.no_grad():
    out = m(torch.from_numpy(lr)[None, None]).clamp(0, 1)[0, 0].numpy()

Path(HERE.parent / "test/cnn-reference.js").write_text(
    "/* GENERATED by cnn/dump_ref.py — PyTorch ground truth for the GLSL port. */\n"
    "window.VUCNNRef = {\n"
    f"  w: {lr.shape[1]}, h: {lr.shape[0]},\n"
    f"  input: {json.dumps([round(float(v),6) for v in lr.ravel()])},\n"
    f"  expected: {json.dumps([round(float(v),6) for v in out.ravel()])},\n"
    "};\n")
print(f"reference: {lr.shape} -> {out.shape}, "
      f"input range {lr.min():.3f}..{lr.max():.3f}, out {out.min():.3f}..{out.max():.3f}")
